#!/bin/sh

# Xcode Cloud Pre-Xcodebuild Script
# Runs immediately before xcodebuild archive/build command
# Used for last-minute setup before the build starts

set -e

echo "Pre-Xcodebuild: Starting..."

# Detect project root
if [ -n "${CI_PRIMARY_REPOSITORY_PATH}" ]; then
    PROJECT_ROOT="${CI_PRIMARY_REPOSITORY_PATH}"
elif [ -n "${CI_WORKSPACE}" ]; then
    PROJECT_ROOT="${CI_WORKSPACE}"
else
    SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
    PROJECT_ROOT="$(dirname "${SCRIPT_DIR}")"
fi

echo "Project root: ${PROJECT_ROOT}"

# =============================================================================
# GENERATE Config.xcconfig FROM XCODE CLOUD ENVIRONMENT VARIABLES
# =============================================================================
# Xcode Cloud env vars are NOT automatically injected into xcconfig files.
# We must write them manually before xcodebuild reads build settings.

XCCONFIG_PATH="${PROJECT_ROOT}/lich-plus/Config.xcconfig"

echo "Generating Config.xcconfig at: ${XCCONFIG_PATH}"

# Validate required variables
if [ -z "${SUPABASE_PROJECT_ID}" ]; then
    echo "Error: SUPABASE_PROJECT_ID environment variable is not set"
    echo "Add it in Xcode Cloud > Workflows > Environment Variables"
    exit 1
fi

if [ -z "${SUPABASE_ANON_KEY}" ]; then
    echo "Error: SUPABASE_ANON_KEY environment variable is not set"
    echo "Add it in Xcode Cloud > Workflows > Environment Variables"
    exit 1
fi

cat > "${XCCONFIG_PATH}" << EOF
// App Configuration - Generated by Xcode Cloud CI
// DO NOT EDIT: This file is auto-generated from Xcode Cloud environment variables

SUPABASE_PROJECT_ID = ${SUPABASE_PROJECT_ID}
SUPABASE_ANON_KEY = ${SUPABASE_ANON_KEY}
EOF

echo "Config.xcconfig generated successfully"

# =============================================================================
# BUILD DIRECTORIES
# =============================================================================

# Create directories that build plugins might need
# This prevents "permission denied" errors when plugins try to create files
echo "Creating build directories..."
mkdir -p "${PROJECT_ROOT}/lich-plus/Resources"
echo "Resources directory ready"

echo "Pre-Xcodebuild: Completed"
