#!/bin/sh

# Xcode Cloud Pre-Xcodebuild Script
# Runs immediately before xcodebuild archive/build command

set -e

echo "Pre-Xcodebuild: Starting..."

export HOMEBREW_NO_INSTALL_CLEANUP=1
export HOMEBREW_NO_ENV_HINTS=1

if [ -n "${CI_PRIMARY_REPOSITORY_PATH}" ]; then
    PROJECT_ROOT="${CI_PRIMARY_REPOSITORY_PATH}"
elif [ -n "${CI_WORKSPACE}" ]; then
    PROJECT_ROOT="${CI_WORKSPACE}"
else
    SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
    PROJECT_ROOT="$(dirname "${SCRIPT_DIR}")"
fi

echo "Project root: ${PROJECT_ROOT}"

# =============================================================================
# GENERATE Config.xcconfig FROM XCODE CLOUD ENVIRONMENT VARIABLES
# =============================================================================
XCCONFIG_PATH="${PROJECT_ROOT}/lich-plus/Config.xcconfig"

echo "Generating Config.xcconfig at: ${XCCONFIG_PATH}"

if [ -z "${SUPABASE_PROJECT_ID}" ]; then
    echo "Error: SUPABASE_PROJECT_ID environment variable is not set"
    echo "Add it in Xcode Cloud > Workflows > Environment Variables"
    exit 1
fi

if [ -z "${SUPABASE_ANON_KEY}" ]; then
    echo "Error: SUPABASE_ANON_KEY environment variable is not set"
    echo "Add it in Xcode Cloud > Workflows > Environment Variables"
    exit 1
fi

cat > "${XCCONFIG_PATH}" << EOF
// App Configuration - Generated by Xcode Cloud CI
// DO NOT EDIT: This file is auto-generated from Xcode Cloud environment variables

SUPABASE_PROJECT_ID = ${SUPABASE_PROJECT_ID}
SUPABASE_ANON_KEY = ${SUPABASE_ANON_KEY}
EOF

echo "Config.xcconfig generated successfully"

# =============================================================================
# BUILD DIRECTORIES
# =============================================================================
echo "Creating build directories..."
mkdir -p "${PROJECT_ROOT}/lich-plus/Resources"
echo "Resources directory ready"

# =============================================================================
# COCOAPODS FALLBACK
# =============================================================================
PODS_RELEASE_XCCONFIG="$(find "${PROJECT_ROOT}/Pods/Target Support Files" -name "Pods-*.release.xcconfig" 2>/dev/null | head -n 1)"

if [ -n "${PODS_RELEASE_XCCONFIG}" ] && [ -f "${PODS_RELEASE_XCCONFIG}" ]; then
    echo "CocoaPods artifacts present: ${PODS_RELEASE_XCCONFIG}"
else
    if [ -f "${PROJECT_ROOT}/Podfile" ]; then
        echo "Warning: CocoaPods artifacts missing — running fallback pod install"

        RUBY_PATH="$(brew --prefix ruby@3.3)/bin"
        export PATH="${RUBY_PATH}:${PATH}"
        export GEM_HOME="${HOME}/.gem"
        export PATH="${GEM_HOME}/bin:${PATH}"

        cd "${PROJECT_ROOT}"
        bundle exec pod install --repo-update

        PODS_RELEASE_XCCONFIG="$(find "${PROJECT_ROOT}/Pods/Target Support Files" -name "Pods-*.release.xcconfig" 2>/dev/null | head -n 1)"
        if [ -z "${PODS_RELEASE_XCCONFIG}" ]; then
            echo "Error: CocoaPods xcconfig still missing after fallback pod install"
            exit 1
        fi
        echo "Fallback pod install succeeded"
    fi
fi

echo "Pre-Xcodebuild: Completed"
